# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import book_pb2 as book__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub:
    """Manages the book catalog.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/neighborhood.library.v1.BookService/CreateBook',
                request_serializer=book__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=book__pb2.CreateBookResponse.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/neighborhood.library.v1.BookService/GetBook',
                request_serializer=book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=book__pb2.GetBookResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/neighborhood.library.v1.BookService/ListBooks',
                request_serializer=book__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=book__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/neighborhood.library.v1.BookService/UpdateBook',
                request_serializer=book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book__pb2.UpdateBookResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/neighborhood.library.v1.BookService/DeleteBook',
                request_serializer=book__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetOverdueBooks = channel.unary_unary(
                '/neighborhood.library.v1.BookService/GetOverdueBooks',
                request_serializer=book__pb2.OverdueBooksRequest.SerializeToString,
                response_deserializer=book__pb2.OverdueBooksResponse.FromString,
                _registered_method=True)
        self.GetOutOfStockBooks = channel.unary_unary(
                '/neighborhood.library.v1.BookService/GetOutOfStockBooks',
                request_serializer=book__pb2.OutOfStockBooksRequest.SerializeToString,
                response_deserializer=book__pb2.OutOfStockBooksResponse.FromString,
                _registered_method=True)


class BookServiceServicer:
    """Manages the book catalog.
    """

    def CreateBook(self, request, context):
        """Add a book.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Get a book by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """List books with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Update a book.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Delete a book.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverdueBooks(self, request, context):
        """List books with overdue loans.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutOfStockBooks(self, request, context):
        """List books with no copies available.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=book__pb2.CreateBookRequest.FromString,
                    response_serializer=book__pb2.CreateBookResponse.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=book__pb2.GetBookRequest.FromString,
                    response_serializer=book__pb2.GetBookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=book__pb2.ListBooksRequest.FromString,
                    response_serializer=book__pb2.ListBooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book__pb2.UpdateBookRequest.FromString,
                    response_serializer=book__pb2.UpdateBookResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=book__pb2.DeleteBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetOverdueBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverdueBooks,
                    request_deserializer=book__pb2.OverdueBooksRequest.FromString,
                    response_serializer=book__pb2.OverdueBooksResponse.SerializeToString,
            ),
            'GetOutOfStockBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutOfStockBooks,
                    request_deserializer=book__pb2.OutOfStockBooksRequest.FromString,
                    response_serializer=book__pb2.OutOfStockBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neighborhood.library.v1.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neighborhood.library.v1.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService:
    """Manages the book catalog.
    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/CreateBook',
            book__pb2.CreateBookRequest.SerializeToString,
            book__pb2.CreateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/GetBook',
            book__pb2.GetBookRequest.SerializeToString,
            book__pb2.GetBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/ListBooks',
            book__pb2.ListBooksRequest.SerializeToString,
            book__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/UpdateBook',
            book__pb2.UpdateBookRequest.SerializeToString,
            book__pb2.UpdateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/DeleteBook',
            book__pb2.DeleteBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverdueBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/GetOverdueBooks',
            book__pb2.OverdueBooksRequest.SerializeToString,
            book__pb2.OverdueBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutOfStockBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.BookService/GetOutOfStockBooks',
            book__pb2.OutOfStockBooksRequest.SerializeToString,
            book__pb2.OutOfStockBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
