# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pb import loan_pb2 as loan__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loan_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoanServiceStub:
    """Manages borrowing and returning books.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BorrowBook = channel.unary_unary(
                '/neighborhood.library.v1.LoanService/BorrowBook',
                request_serializer=loan__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=loan__pb2.BorrowBookResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/neighborhood.library.v1.LoanService/ReturnBook',
                request_serializer=loan__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=loan__pb2.ReturnBookResponse.FromString,
                _registered_method=True)
        self.GetLoan = channel.unary_unary(
                '/neighborhood.library.v1.LoanService/GetLoan',
                request_serializer=loan__pb2.GetLoanRequest.SerializeToString,
                response_deserializer=loan__pb2.GetLoanResponse.FromString,
                _registered_method=True)
        self.ListLoans = channel.unary_unary(
                '/neighborhood.library.v1.LoanService/ListLoans',
                request_serializer=loan__pb2.ListLoansRequest.SerializeToString,
                response_deserializer=loan__pb2.ListLoansResponse.FromString,
                _registered_method=True)


class LoanServiceServicer:
    """Manages borrowing and returning books.
    """

    def BorrowBook(self, request, context):
        """Borrow a book (creates a loan).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Return a borrowed book.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoan(self, request, context):
        """Get a loan by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoans(self, request, context):
        """List loans with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=loan__pb2.BorrowBookRequest.FromString,
                    response_serializer=loan__pb2.BorrowBookResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=loan__pb2.ReturnBookRequest.FromString,
                    response_serializer=loan__pb2.ReturnBookResponse.SerializeToString,
            ),
            'GetLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoan,
                    request_deserializer=loan__pb2.GetLoanRequest.FromString,
                    response_serializer=loan__pb2.GetLoanResponse.SerializeToString,
            ),
            'ListLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoans,
                    request_deserializer=loan__pb2.ListLoansRequest.FromString,
                    response_serializer=loan__pb2.ListLoansResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neighborhood.library.v1.LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neighborhood.library.v1.LoanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoanService:
    """Manages borrowing and returning books.
    """

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.LoanService/BorrowBook',
            loan__pb2.BorrowBookRequest.SerializeToString,
            loan__pb2.BorrowBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.LoanService/ReturnBook',
            loan__pb2.ReturnBookRequest.SerializeToString,
            loan__pb2.ReturnBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.LoanService/GetLoan',
            loan__pb2.GetLoanRequest.SerializeToString,
            loan__pb2.GetLoanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.LoanService/ListLoans',
            loan__pb2.ListLoansRequest.SerializeToString,
            loan__pb2.ListLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
