# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from app.pb import member_pb2 as member__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in member_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemberServiceStub:
    """Manages library members.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMember = channel.unary_unary(
                '/neighborhood.library.v1.MemberService/CreateMember',
                request_serializer=member__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.CreateMemberResponse.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/neighborhood.library.v1.MemberService/GetMember',
                request_serializer=member__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=member__pb2.GetMemberResponse.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/neighborhood.library.v1.MemberService/ListMembers',
                request_serializer=member__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=member__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/neighborhood.library.v1.MemberService/UpdateMember',
                request_serializer=member__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=member__pb2.UpdateMemberResponse.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/neighborhood.library.v1.MemberService/DeleteMember',
                request_serializer=member__pb2.DeleteMemberRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MemberServiceServicer:
    """Manages library members.
    """

    def CreateMember(self, request, context):
        """Register a member.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Get a member by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """List members with optional filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Update a member.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Delete a member.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=member__pb2.CreateMemberRequest.FromString,
                    response_serializer=member__pb2.CreateMemberResponse.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=member__pb2.GetMemberRequest.FromString,
                    response_serializer=member__pb2.GetMemberResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=member__pb2.ListMembersRequest.FromString,
                    response_serializer=member__pb2.ListMembersResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=member__pb2.UpdateMemberRequest.FromString,
                    response_serializer=member__pb2.UpdateMemberResponse.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=member__pb2.DeleteMemberRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neighborhood.library.v1.MemberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neighborhood.library.v1.MemberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemberService:
    """Manages library members.
    """

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.MemberService/CreateMember',
            member__pb2.CreateMemberRequest.SerializeToString,
            member__pb2.CreateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.MemberService/GetMember',
            member__pb2.GetMemberRequest.SerializeToString,
            member__pb2.GetMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.MemberService/ListMembers',
            member__pb2.ListMembersRequest.SerializeToString,
            member__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.MemberService/UpdateMember',
            member__pb2.UpdateMemberRequest.SerializeToString,
            member__pb2.UpdateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neighborhood.library.v1.MemberService/DeleteMember',
            member__pb2.DeleteMemberRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
